name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./package

      - name: Copy application code to the package directory
        run: cp main.py ./package/

      - name: Create a deployment package
        run: |
          cd package
          zip -r ../deployment.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the S3 bucket with the AWS CLI
        run: aws s3 cp deployment.zip s3://${{ secrets.AWS_BUCKET_NAME }}
